// Multi-view silhouette optimization: deform an icosphere toward the bunny
// using vertex-position gradients, with two selectable techniques:
//
//   --technique=hardsoftras (default)
//     HardSoftRas (Dressi paper Alg.2): the rasterizer supplies a face-ID
//     buffer (with Eq.3 depth shift and optional --peels=K depth peeling);
//     the pixel-to-edge distance is built from image-space ops over
//     FaceFetch'd corner positions, so the whole backward is generated by
//     the AD. FaceFetch's backward is the paper's inverse-table-style
//     stochastic gather (Alg.1 philosophy).
//
//   --technique=aa
//     Screen-space AA (Dr.Hair, arXiv:2403.17496 Eq.3-5): hard
//     rasterization plus a differentiable blend across triangle-ID
//     boundaries; the vertex backward samples the edges stochastically
//     (--samples, 0 = exact).
//
// The whole iteration lives on the GPU (the paper's transfer model:
// upload once, download at the end): positions, projections, soft
// geometry, regularizers and Adam state are graph ops / copy-backs, and
// per-iteration CPU traffic is zero. --single-view additionally follows
// the paper's experiment methodology: each iteration renders ONE camera,
// selected in-graph (view = iteration counter mod n_views), cutting the
// per-iteration pass count by n_views.

#include "run.h"

#include <spdlog/cfg/env.h>
#include <spdlog/spdlog.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <string>
#include <vector>

#include "../common/asset_utils.h"
#include "../common/bench.h"
#include "../common/geometry_utils.h"
#include "dressi/dressi.h"

using namespace dressi;
using namespace dressi_examples;

namespace {

struct Options {
    std::string data_dir = "data/bunny";
    std::string out_dir;       // empty = "silopt_out_<technique>"
    std::string mesh_path;     // glTF self-reconstruction benchmark
    float init_scale = 0.8f;   // initial shrink for --mesh
    std::string technique = "hardsoftras";
    uint32_t n_views = 8;
    uint32_t screen = 128;
    int n_iters = 150;  // IoU plateaus by ~150 (0.951 vs 0.956 at 300)
    uint32_t sphere_level = 3;
    float radius_px = 3.f;
    uint32_t samples = 8;  // stochastic backward samples per face
    uint32_t peels = 1;    // hardsoftras depth-peeling layers (K)
    bool single_view = false;  // one (cycled) camera per iteration
    bool no_view = false;      // skip the live viewer (clean benchmarking)
    int view_interval = 1;     // live-viewer refresh cadence (iters); 0 = off
    // Regularizer weights relative to the data-gradient RMS; negative =
    // per-technique default (hardsoftras: 0.15/0.4; aa: 0.5/0.5)
    float laplacian = -1.f;
    float normal = -1.f;
    float lr = 0.01f;
};

Options ParseArgs(const std::vector<std::string>& args) {
    Options opt;
    for (const std::string& a : args) {
        std::string key, value;
        if (const size_t eq = a.find('=');
            a.rfind("--", 0) == 0 && eq != std::string::npos) {
            key = a.substr(0, eq);
            value = a.substr(eq + 1);
        }
        if (key == "--technique") {
            opt.technique = value;
        } else if (key == "--data-dir") {
            opt.data_dir = value;
        } else if (key == "--out-dir") {
            opt.out_dir = value;
        } else if (key == "--mesh") {
            opt.mesh_path = value;
        } else if (key == "--init-scale") {
            opt.init_scale = std::stof(value);
        } else if (key == "--views") {
            opt.n_views = uint32_t(std::stoul(value));
        } else if (key == "--screen") {
            opt.screen = uint32_t(std::stoul(value));
        } else if (key == "--iters") {
            opt.n_iters = std::stoi(value);
        } else if (key == "--sphere-level") {
            opt.sphere_level = uint32_t(std::stoul(value));
        } else if (key == "--samples") {
            opt.samples = uint32_t(std::stoul(value));
        } else if (key == "--peels") {
            opt.peels = std::max(1u, uint32_t(std::stoul(value)));
        } else if (key == "--single-view") {
            opt.single_view = value == "1" || value == "true";
        } else if (key == "--no-view") {
            opt.no_view = value == "1" || value == "true";
        } else if (key == "--view-interval") {
            opt.view_interval = std::stoi(value);
        } else if (key == "--lr") {
            opt.lr = std::stof(value);
        } else if (key == "--laplacian") {
            opt.laplacian = std::stof(value);
        } else if (key == "--normal") {
            opt.normal = std::stof(value);
        } else if (a.rfind("--", 0) != 0) {
            opt.data_dir = a;
        } else {
            throw DressiError("unknown option: " + a);
        }
    }
    if (opt.technique != "hardsoftras" && opt.technique != "aa") {
        throw DressiError("--technique must be hardsoftras or aa");
    }
    const bool hs = opt.technique == "hardsoftras";
    if (opt.laplacian < 0.f) {
        opt.laplacian = hs ? 0.15f : 0.5f;
    }
    if (opt.normal < 0.f) {
        opt.normal = hs ? 0.4f : 0.5f;
    }
    return opt;
}

float MaskIoU(const CpuImage& a, const CpuImage& b) {
    size_t inter = 0, uni = 0;
    for (size_t i = 0; i < a.data.size(); i++) {
        const bool pa = a.data[i] > 0.5f;
        const bool pb = b.data[i] > 0.5f;
        inter += (pa && pb);
        uni += (pa || pb);
    }
    return uni ? float(inter) / float(uni) : 1.f;
}

}  // namespace

int dressi_examples::RunSilhouetteOptimization(
        const std::vector<std::string>& args, ExampleHost& host) try {
    spdlog::cfg::load_env_levels();
    const Options opt = ParseArgs(args);
    const ImgSize screen = {opt.screen, opt.screen};
    const bool hardsoft = opt.technique == "hardsoftras";
    const std::string out_dir = opt.out_dir.empty()
                                        ? "silopt_out_" + opt.technique
                                        : opt.out_dir;
    std::filesystem::create_directories(out_dir);

    // ------------------------- Assets / geometry -------------------------
    // Default: deform an icosphere toward the bunny. With --mesh=<gltf>:
    // self-reconstruction of the loaded mesh from a shrunken copy (the
    // paper's geometry-optimization benchmark shape, e.g. the Avocado)
    Mesh bunny;   // target geometry
    Mesh sphere;  // optimized geometry
    if (!opt.mesh_path.empty()) {
        bunny = LoadGltfMesh(opt.mesh_path);
        sphere = bunny;
        for (float& p : sphere.pos.data) {
            p *= opt.init_scale;
        }
    } else {
        bunny = LoadObjMesh(opt.data_dir + "/bunny.obj");
        sphere = GenerateIcosphere(opt.sphere_level);
        for (float& p : sphere.pos.data) {
            p *= 0.55f;
        }
    }
    const uint32_t n_verts = sphere.numVertices();
    const uint32_t n_faces = sphere.numFaces();
    spdlog::info("technique {}{}: bunny {}v/{}f -> sphere {}v/{}f, "
                 "{} views, {}x{} screen, K={}",
                 opt.technique, opt.single_view ? " (single-view)" : "",
                 bunny.numVertices(), bunny.numFaces(), n_verts, n_faces,
                 opt.n_views, screen.w, screen.h, opt.peels);

    // ------------------------------ Cameras ------------------------------
    const Mat4 proj =
            PerspectiveVk(45.f * 3.14159265f / 180.f, 1.f, 0.1f, 10.f);
    std::vector<Mat4> mvps(opt.n_views);
    for (uint32_t v = 0; v < opt.n_views; v++) {
        const float ang = 2.f * 3.14159265f * float(v) / float(opt.n_views);
        const float elev = (v % 2 == 0) ? 0.55f : -0.35f;
        const std::array<float, 3> eye = {1.6f * std::sin(ang), elev,
                                          1.6f * std::cos(ang)};
        mvps[v] = Mul(proj, LookAt(eye, {0, 0, 0}, {0, 1, 0}));
    }

    // --------------------------- Static leaves ---------------------------
    const CpuImage b_vf_img = VertexFacesTex(bunny.faces,
                                             bunny.numVertices());
    const CpuImage s_vf_img = VertexFacesTex(sphere.faces, n_verts);
    const CpuImage s_vn_img = VertexNeighborsTex(sphere.faces, n_verts);
    const CpuImage s_fa_img = FaceNeighborsTex(sphere.faces);
    Variable b_ones(FLOAT, {bunny.numVertices(), 1});
    Variable b_faces_i(IVEC3, {bunny.numFaces(), 1});
    Variable b_faces_f(VEC3, {bunny.numFaces(), 1});
    Variable b_vtx_faces(FLOAT, b_vf_img.getImgSize());
    Variable s_ones(FLOAT, {n_verts, 1});
    Variable s_faces_i(IVEC3, {n_faces, 1});
    Variable s_faces_f(VEC3, {n_faces, 1});
    Variable s_vtx_faces(FLOAT, s_vf_img.getImgSize());
    Variable s_vtx_nbrs(FLOAT, s_vn_img.getImgSize());
    Variable s_face_adj(VEC3, {n_faces, 1});
    Variable s_face_id(FLOAT, {n_faces * 3, 1});   // hardsoftras
    Variable s_faces_soft(IVEC3, {n_faces, 1});    // hardsoftras

    // Optimization state (GPU-resident via the end-of-frame copy-backs)
    Variable pos(VEC3, {n_verts, 1});     // the optimizer target
    Variable adam_m(VEC3, {n_verts, 1});
    Variable adam_v(VEC3, {n_verts, 1});
    Variable adam_t(FLOAT, {1, 1});
    Variable zero_seed(FLOAT, {1, 1});  // static seed for frozen branches
    // Single-view mode: per-view MVP columns / target masks as atlases
    Variable mvp_atlas(VEC4, {4, opt.n_views});
    Variable target_atlas(FLOAT, {screen.w, screen.h * opt.n_views});

    // ------------------ Technique-specific prediction --------------------
    const float sigma_scale = 7.f / opt.radius_px;
    const auto build_pred = [&](const Variable& clip_v) -> Variable {
        if (!hardsoft) {
            Variable mask = F::Rasterize(clip_v, s_ones, s_faces_i, screen);
            Variable tri = F::RasterizeFaceId(clip_v, s_ones, s_faces_i,
                                              screen);
            // Stochastic vertex backward, jittered by the in-graph
            // iteration counter
            return F::AntiAlias(mask, tri, clip_v, s_faces_f, s_vtx_faces,
                                adam_t, opt.samples);
        }
        Variable soft_clip =
                F::SoftClip(clip_v, s_faces_f, screen, opt.radius_px);
        // Per-face corner clip positions (differentiable, exact bwd)
        Variable tri0 = F::LookupFaces(clip_v, s_faces_f, s_vtx_faces, 0);
        Variable tri1 = F::LookupFaces(clip_v, s_faces_f, s_vtx_faces, 1);
        Variable tri2 = F::LookupFaces(clip_v, s_faces_f, s_vtx_faces, 2);
        Variable pc = F::ScreenCoord(screen);
        Variable zero = F::Float(0.f);
        Variable one = F::Float(1.f);

        // D_k = mask * sigmoid(dist / sigma) from a face-ID buffer with
        // image-space ops (backward: FaceFetch sampling + AD; adam_t is
        // the per-iteration jitter seed)
        const auto soft_prob = [&](const Variable& idx) {
            Variable mask = F::Greater(idx, F::Float(0.5f));
            const auto fetch = [&](const Variable& tri) {
                return F::FaceFetch(tri, idx, tri0, tri1, tri2, adam_t,
                                    opt.radius_px, opt.samples);
            };
            const auto screen_of = [&](const Variable& c) {
                Variable w = F::GetW(c) + (1.f - mask);
                Variable sx = (F::GetX(c) / w * 0.5f + 0.5f) *
                              float(screen.w);
                Variable sy = (F::GetY(c) / w * 0.5f + 0.5f) *
                              float(screen.h);
                return F::Vec2(sx, sy);
            };
            Variable s0 = screen_of(fetch(tri0));
            Variable s1 = screen_of(fetch(tri1));
            Variable s2 = screen_of(fetch(tri2));
            const auto edge_dist = [&](const Variable& a,
                                       const Variable& b) {
                Variable e = b - a;
                Variable t = F::Clamp(F::Dot(pc - a, e) /
                                              (F::Dot(e, e) + 1e-12f),
                                      zero, one);
                Variable dd = pc - (a + t * e);
                return F::Sqrt(F::Dot(dd, dd) + 1e-12f);
            };
            const auto edge_cross = [&](const Variable& a,
                                        const Variable& b) {
                Variable e = b - a;
                return F::GetX(e) * (F::GetY(pc) - F::GetY(a)) -
                       F::GetY(e) * (F::GetX(pc) - F::GetX(a));
            };
            Variable dmin = F::Min(F::Min(edge_dist(s0, s1),
                                          edge_dist(s1, s2)),
                                   edge_dist(s2, s0));
            Variable cr0 = edge_cross(s0, s1);
            Variable cr1 = edge_cross(s1, s2);
            Variable cr2 = edge_cross(s2, s0);
            Variable inside =
                    F::Min(F::Step(zero, cr0) * F::Step(zero, cr1) *
                                           F::Step(zero, cr2) +
                                   F::Step(zero, -cr0) *
                                           F::Step(zero, -cr1) *
                                           F::Step(zero, -cr2),
                           one);
            Variable dist = (inside * 2.f - 1.f) * dmin;
            return mask * F::Sigmoid(dist * sigma_scale);
        };

        // Alg.2 depth peeling: peel k discards fragments at or in front
        // of peel k-1's shifted depth; Eq.6: I_s = 1 - prod_k (1 - D_k)
        Variable one_minus = one;
        Variable prev_shift(nullptr);
        Variable hard(nullptr);
        for (uint32_t peel = 0; peel < opt.peels; peel++) {
            Variable rs = F::StopGradient(
                    peel == 0 ? F::RasterizeSoft(soft_clip, s_face_id,
                                                 s_faces_soft, clip_v,
                                                 s_faces_f, s_vtx_faces,
                                                 screen, opt.radius_px)
                              : F::RasterizeSoft(soft_clip, s_face_id,
                                                 s_faces_soft, clip_v,
                                                 s_faces_f, s_vtx_faces,
                                                 prev_shift, screen,
                                                 opt.radius_px));
            // Next peel's threshold: this layer's Eq.3 shifted depth
            // rebuilt from the output channels (0 at background)
            Variable dist_c = F::GetX(rs);
            Variable cov = F::GetW(rs);
            Variable ge = F::Step(zero, dist_c);
            prev_shift =
                    cov * (ge * (F::Clamp(F::GetZ(rs), zero, one) * 0.5f) +
                           (1.f - ge) *
                                   (F::Clamp(-dist_c * (1.f /
                                                        opt.radius_px),
                                             zero, one) *
                                            0.5f +
                                    0.5f));
            Variable idx = (F::GetY(rs) + 1.f) * cov;
            one_minus = one_minus * (1.f - soft_prob(idx));
            if (peel == 0) {
                // Hard coverage from the frontal peel's channels (covered
                // AND dist >= 0) -- no extra rasterization pass
                hard = cov * ge;
            }
        }
        Variable soft_sil = 1.f - one_minus;
        // Paper Eq.5 spirit: non-edge pixels keep the hard value; the
        // sigmoid band supplies the gradients around the silhouette
        return F::Max(hard, soft_sil);
    };

    // Frozen per-view target masks (bunny silhouettes; AA'd for the aa
    // technique so pred can match exactly)
    const auto build_target = [&](const Variable& tgt_clip) -> Variable {
        Variable t_mask = F::Rasterize(tgt_clip, b_ones, b_faces_i, screen);
        if (hardsoft) {
            return F::StopGradient(t_mask);
        }
        Variable t_tri =
                F::RasterizeFaceId(tgt_clip, b_ones, b_faces_i, screen);
        return F::StopGradient(F::AntiAlias(t_mask, t_tri, tgt_clip,
                                            b_faces_f, b_vtx_faces,
                                            zero_seed, 0));
    };

    // ------------------------------ Graph --------------------------------
    // Either one prediction per camera (all views each iteration) or one
    // dynamic prediction whose camera cycles in-graph (single-view)
    Variables targets, preds;   // per graph-view
    std::vector<Variable> tgt_clips;
    Variables view_losses;
    if (opt.single_view) {
        // Random viewpoint per iteration (the paper's methodology): a
        // deterministic cycle resonates with Adam's momentum window, so
        // pick the camera with an in-graph sine hash of the counter
        Variable view_idx = F::Floor(
                F::Fract(F::Sin(adam_t * 12.9898f + 78.233f) *
                         43758.5453f) *
                float(opt.n_views));
        Variable m0 = F::PixelFetch(mvp_atlas, 0, view_idx);
        Variable m1 = F::PixelFetch(mvp_atlas, 1, view_idx);
        Variable m2 = F::PixelFetch(mvp_atlas, 2, view_idx);
        Variable m3 = F::PixelFetch(mvp_atlas, 3, view_idx);
        Variable clip_v = m0 * F::GetX(pos) + m1 * F::GetY(pos) +
                          m2 * F::GetZ(pos) + m3;
        targets.push_back(
                F::TileFetch(target_atlas, view_idx, screen.h));
        preds.push_back(build_pred(clip_v));
        Variable diff = targets[0] - preds[0];
        view_losses.push_back(diff * diff *
                              (1.f / float(screen.w * screen.h)));
    } else {
        for (uint32_t v = 0; v < opt.n_views; v++) {
            tgt_clips.emplace_back(VEC4, ImgSize{bunny.numVertices(), 1});
            targets.push_back(build_target(tgt_clips.back()));
            preds.push_back(
                    build_pred(TransformToClipVar(pos, mvps[v])));
            Variable diff = targets[v] - preds[v];
            view_losses.push_back(diff * diff *
                                  (1.f / float(screen.w * screen.h)));
        }
    }
    Variable loss = F::SumPixelWise(view_losses);  // {S,S} loss image
    Variable pos_mut = pos;
    pos_mut.setRequiresGradRecursively();

    // ----------------- In-graph Adam + regularizers ----------------------
    DressiAD ad;
    ad.setLossVar(loss);
    bool state_registered = false;
    ad.setOptimizer([&](Variables xs, Variables gxs) {
        DRESSI_CHECK(xs.size() == 1 && xs[0] == pos,
                     "expected pos as the only optimizer target");
        // Regularizers, weighted relative to the data-gradient RMS
        // (SumAll: one pass instead of the log-step reduction chain)
        const float inv_cnt = 1.f / float(n_verts * 3);
        const auto rms = [&](const Variable& x) {
            return F::Sqrt(F::SumAll(x * x) * inv_cnt + 1e-24f);
        };
        Variable g = gxs[0];
        Variable data_rms = rms(g);
        Variable g_lap = pos - F::VertexNeighborMean(pos, s_vtx_nbrs);
        Variable g_nrm = F::NormalConsistencyVertexGrad(
                F::NormalConsistencyFaceTerm(pos, s_faces_f, s_face_adj),
                pos, s_faces_f, s_vtx_faces);
        g = g + g_lap * (data_rms / rms(g_lap) * opt.laplacian) +
            g_nrm * (data_rms / rms(g_nrm) * opt.normal);
        // Adam with GPU-resident state
        const float b1 = 0.9f, b2 = 0.999f, eps = 1e-8f;
        Variable t_new = adam_t + 1.f;
        Variable m_new = adam_m * b1 + g * (1.f - b1);
        Variable v_new = adam_v * b2 + g * g * (1.f - b2);
        Variable bc1 = 1.f - F::Pow(F::Float(b1), t_new);
        Variable bc2 = 1.f - F::Pow(F::Float(b2), t_new);
        Variable step = (m_new / bc1) /
                        (F::Sqrt(v_new / bc2) + eps) * opt.lr;
        if (!state_registered) {
            ad.addUpdate(adam_m, m_new);
            ad.addUpdate(adam_v, v_new);
            ad.addUpdate(adam_t, t_new);
            state_registered = true;
        }
        return Variables{pos - step};
    });
    for (size_t i = 0; i < preds.size(); i++) {
        ad.markOutput(targets[i]);
        ad.markOutput(preds[i]);
    }

    // ------------------- One-time uploads (then GPU-only) -----------------
    const CpuImage b_ones_img(bunny.numVertices(), 1, 1, 1.f);
    const CpuImage s_ones_img(n_verts, 1, 1, 1.f);
    ad.sendImg(b_ones, b_ones_img);
    ad.sendImg(b_faces_i, bunny.faces);
    ad.sendImg(b_faces_f, bunny.faces);
    ad.sendImg(b_vtx_faces, b_vf_img);
    ad.sendImg(s_ones, s_ones_img);
    ad.sendImg(s_faces_i, sphere.faces);
    ad.sendImg(s_faces_f, sphere.faces);
    ad.sendImg(s_vtx_faces, s_vf_img);
    ad.sendImg(s_vtx_nbrs, s_vn_img);
    ad.sendImg(s_face_adj, s_fa_img);
    if (hardsoft) {
        CpuImage face_id_img(n_faces * 3, 1, 1);
        CpuImage faces_soft_img(n_faces, 1, 3);
        for (uint32_t f = 0; f < n_faces; f++) {
            for (uint32_t k = 0; k < 3; k++) {
                face_id_img.at(f * 3 + k, 0, 0) = float(f);
                faces_soft_img.at(f, 0, k) = float(f * 3 + k);
            }
        }
        ad.sendImg(s_face_id, face_id_img);
        ad.sendImg(s_faces_soft, faces_soft_img);
    }
    ad.sendImg(pos, sphere.pos);
    ad.sendImg(adam_m, CpuImage(n_verts, 1, 3, 0.f));
    ad.sendImg(adam_v, CpuImage(n_verts, 1, 3, 0.f));
    ad.sendImg(adam_t, CpuImage(1, 1, 1, 0.f));
    if (!hardsoft) {
        ad.sendImg(zero_seed, CpuImage(1, 1, 1, 0.f));
    }

    std::vector<CpuImage> target_imgs(opt.n_views);
    if (opt.single_view) {
        // Pre-render all target masks ONCE on a throwaway DressiAD and
        // upload them as an atlas; the MVP columns become an atlas too
        {
            DressiAD tgt_ad;
            std::vector<Variable> clips;
            Variables masks;
            for (uint32_t v = 0; v < opt.n_views; v++) {
                clips.emplace_back(VEC4, ImgSize{bunny.numVertices(), 1});
                masks.push_back(build_target(clips.back()));
                tgt_ad.markOutput(masks.back());
            }
            tgt_ad.setLossVar(masks[0]);
            tgt_ad.sendImg(b_ones, b_ones_img);
            tgt_ad.sendImg(b_faces_i, bunny.faces);
            tgt_ad.sendImg(b_faces_f, bunny.faces);
            tgt_ad.sendImg(b_vtx_faces, b_vf_img);
            if (!hardsoft) {
                tgt_ad.sendImg(zero_seed, CpuImage(1, 1, 1, 0.f));
            }
            for (uint32_t v = 0; v < opt.n_views; v++) {
                tgt_ad.sendImg(clips[v],
                               TransformToClip(bunny.pos, mvps[v]));
            }
            tgt_ad.execStep();
            for (uint32_t v = 0; v < opt.n_views; v++) {
                target_imgs[v] = tgt_ad.recvImg(masks[v]);
            }
        }
        CpuImage atlas(screen.w, screen.h * opt.n_views, 1);
        for (uint32_t v = 0; v < opt.n_views; v++) {
            std::copy(target_imgs[v].data.begin(),
                      target_imgs[v].data.end(),
                      atlas.data.begin() +
                              int64_t(size_t(v) * screen.w * screen.h));
        }
        ad.sendImg(target_atlas, atlas);
        CpuImage mvp_img(4, opt.n_views, 4);
        for (uint32_t v = 0; v < opt.n_views; v++) {
            for (uint32_t c = 0; c < 4; c++) {
                for (uint32_t r = 0; r < 4; r++) {
                    mvp_img.at(c, v, r) = mvps[v][size_t(c) * 4 + r];
                }
            }
        }
        ad.sendImg(mvp_atlas, mvp_img);
    } else {
        for (uint32_t v = 0; v < opt.n_views; v++) {
            ad.sendImg(tgt_clips[v], TransformToClip(bunny.pos, mvps[v]));
        }
    }

    // ------------------------------ Viewer --------------------------------
    const uint32_t tile_cols = opt.single_view ? 1 : 4;
    const uint32_t n_tiles = uint32_t(preds.size());
    const uint32_t tile_rows = (n_tiles + tile_cols - 1) / tile_cols;
    const uint32_t win_w = screen.w * tile_cols;
    std::unique_ptr<IViewer> viewer_target, viewer_pred;
    if (!opt.no_view) {
        viewer_target = host.makeViewer(win_w, screen.h * tile_rows,
                                        "bunny silhouette targets");
        viewer_pred = host.makeViewer(win_w, screen.h * tile_rows,
                                      "optimized silhouette");
        viewer_target->setPosition(80, 80);
        viewer_pred->setPosition(80 + int(win_w) + 16, 80);
    }
    bool viewer_open = viewer_target && viewer_target->valid() &&
                       viewer_pred->valid();
    if (!viewer_open && !opt.no_view) {
        spdlog::warn("live viewer unavailable; continuing headless");
    }
    const int view_interval = opt.view_interval;
    CpuImage target_tile;

    // ---------------------------- Optimization ----------------------------
    const auto loss_value = [&]() {
        const CpuImage li = ad.recvImg(loss);
        double s = 0.0;
        for (float v : li.data) {
            s += v;
        }
        return float(s);
    };

    using Clock = std::chrono::steady_clock;
    std::vector<double> opt_samples;  // per-iter execStep ms (steady state)
    std::vector<double> warmup_samples;  // the excluded build/rebuild iters
    double view_ms = 0.0;
    float first_loss = 0.f;
    float last_loss = 0.f;
    // Benchmark methodology (see CLAUDE.md "Benchmarking"): report the
    // MEDIAN steady-state execStep, excluding a warmup that covers the
    // one-time full build + the reactive fast/full rebuilds (~250 ms).
    // Median (not mean) is robust to the host-side scheduling jitter that
    // dominates when GPU work is only ~100 us; it is how the README /
    // paper-comparison figures are produced.
    const int opt_warmup = std::min(20, opt.n_iters / 2);
    for (int iter = 0; iter < opt.n_iters; iter++) {
        if (host.cancelled()) {
            break;
        }
        const auto t0 = Clock::now();
        ad.execStep();
        const double iter_ms =
                std::chrono::duration<double, std::milli>(Clock::now() - t0)
                        .count();
        if (iter >= opt_warmup) {
            opt_samples.push_back(iter_ms);
        } else {
            warmup_samples.push_back(iter_ms);
        }

        if (iter == 0) {
            first_loss = loss_value();
            std::vector<CpuImage> tgts, prds;
            for (size_t i = 0; i < preds.size(); i++) {
                tgts.push_back(ad.recvImg(targets[i]));
                prds.push_back(ad.recvImg(preds[i]));
            }
            target_tile = TileImages(tgts, tile_cols);
            SaveImagePng(out_dir + "/targets.png", target_tile);
            SaveImagePng(out_dir + "/pred_first.png",
                         TileImages(prds, tile_cols));
        }
        if (viewer_open && view_interval > 0 && iter % view_interval == 0) {
            const auto tv0 = Clock::now();
            std::vector<CpuImage> prds;
            for (size_t i = 0; i < preds.size(); i++) {
                prds.push_back(ad.recvImg(preds[i]));
            }
            if (opt.single_view) {
                target_tile = ad.recvImg(targets[0]);
            }
            viewer_pred->setTitle(fmt::format("optimized silhouette  iter {}",
                                              iter));
            viewer_open = viewer_pred->update(TileImages(prds, tile_cols)) &&
                          viewer_target->update(target_tile);
            view_ms += std::chrono::duration<double, std::milli>(
                               Clock::now() - tv0)
                               .count();
        }
        if (iter % 20 == 0 || iter == opt.n_iters - 1) {
            double med = 0.0;
            if (!opt_samples.empty()) {
                std::vector<double> s = opt_samples;
                std::sort(s.begin(), s.end());
                med = s[s.size() / 2];
            }
            spdlog::info("iter {:4d}  loss {:.8f}  opt {:.3f} ms/iter"
                         "  (median steady-state, {} warmup iters excluded;"
                         " view {:.1f} ms/iter excluded)",
                         iter, loss_value(), med, opt_warmup,
                         view_ms / double(iter + 1));
        }
    }

    // --------------------- Final download / outputs ----------------------
    // Cycle one extra round so every camera reports its IoU (pred/target
    // pairs are read back per step; positions move negligibly)
    float mean_iou = 0.f;
    std::vector<CpuImage> final_preds;
    if (opt.single_view) {
        for (uint32_t v = 0; v < opt.n_views; v++) {
            ad.execStep();
            final_preds.push_back(ad.recvImg(preds[0]));
            mean_iou += MaskIoU(final_preds.back(),
                                ad.recvImg(targets[0]));
        }
    } else {
        ad.execStep();
        for (uint32_t v = 0; v < opt.n_views; v++) {
            final_preds.push_back(ad.recvImg(preds[v]));
            mean_iou += MaskIoU(final_preds.back(),
                                ad.recvImg(targets[v]));
        }
    }
    mean_iou /= float(opt.n_views);
    last_loss = loss_value();
    const CpuImage final_pos = ad.recvImg(pos);
    sphere.pos.data = final_pos.data;

    SaveImagePng(out_dir + "/pred_last.png",
                 TileImages(final_preds, opt.single_view ? 4 : tile_cols));
    SaveObjMesh(out_dir + "/optimized.obj", sphere);

    const auto face_adj = BuildFaceAdjacency(sphere.faces);
    const uint32_t flipped =
            CountFlippedFacePairs(sphere.pos, sphere.faces, face_adj);
    spdlog::info("loss {:.8f} -> {:.8f} ({:.1f}x), mean silhouette IoU"
                 " {:.4f}, flipped face pairs {} / {}",
                 first_loss, last_loss,
                 first_loss / std::max(last_loss, 1e-12f), mean_iou,
                 flipped, face_adj.size());

    // Benchmark record for scripts/bench_summary.py (median steady-state
    // execStep ms/iter, warmup excluded — CLAUDE.md "Benchmarking")
    const double median_ms = MedianMs(opt_samples);
    const double warmup_ms = WarmupMs(warmup_samples, median_ms);
    const double first_build_ms =
            warmup_samples.empty() ? 0.0 : warmup_samples.front();
    spdlog::info("one-time build/warmup {:.1f} ms (first build {:.1f} ms)",
                 warmup_ms, first_build_ms);
    {
        BenchRecord rec("silhouette_optimization", ad.getDeviceName());
        rec.addPacking(ad.getFuncCount(), ad.getSubStageCount(),
                       ad.getStageCount());
        rec.add("technique", opt.technique);
        rec.add("screen", int64_t(opt.screen));
        rec.add("views", int64_t(opt.n_views));
        rec.add("iters", int64_t(opt.n_iters));
        rec.add("samples", int64_t(opt.samples));
        rec.add("peels", int64_t(opt.peels));
        rec.add("single_view", opt.single_view);
        rec.add("median_ms_per_iter", median_ms);
        rec.add("warmup_excluded", int64_t(opt_warmup));
        rec.add("warmup_ms", warmup_ms, 1);
        rec.add("first_build_ms", first_build_ms, 1);
        rec.add("mean_iou", double(mean_iou));
        rec.add("loss_drop",
                double(first_loss / std::max(last_loss, 1e-12f)), 1);
        rec.save(out_dir + "/bench.json");
    }
    spdlog::info("outputs in {}/", out_dir);
    return (last_loss < first_loss / 5.f && mean_iou > 0.85f) ? 0 : 1;
} catch (const std::exception& e) {
    spdlog::error("error: {}", e.what());
    return 2;
}
